export const SET_LIST_FURNITURE = 'SET_LIST_FURNITURE';
export const SET_LIST_FURNITURE_STYLE = 'SET_LIST_FURNITURE_STYLE';
export const SET_LIST_FURNITURE_BASED_KEYWORD = 'SET_LIST_FURNITURE_BASED_KEYWORD';
export const SET_LIST_FURNITURE_BASED_TYPE = 'SET_LIST_FURNITURE_BASED_TYPE';
export const SET_LIST_FURNITURE_BASED_DELIVER = 'SET_LIST_FURNITURE_BASED_DELIVER';
export const SET_LIST_FURNITURE_BASED_ALL_FILTER = 'SET_LIST_FURNITURE_BASED_ALL_FILTER';
